### ISSUE TITLE
اضافه کردن لایسنس

### ISSUE THREAD

**Issue by arsalanses** [kokabi1365/Vajehdan#12]
سلام،
فکر کنم بهتره یه لایسنس به ریپازیتوری گیتهاب اضافه کنید
پیشنهاد من GPL v2 هست ;)

**Comment by kokabi1365** [comment]
سلام،
در نظر دارم این کار رو بکنم ولی هنوز در مورد انتخاب لایسنس تصمیم نگرفتم.
ممنون از شما.

**Comment by kokabi1365** [comment]
<div dir="rtl">لایسنس AGPL اضافه شد.</div>
