### ISSUE TITLE
Windows Defender

### ISSUE THREAD

**Issue by arsalanses** [kokabi1365/Vajehdan#13]
ویندوز دیفندر برنامه رو مخرب تشخیص میده :(

![image](https://user-images.githubusercontent.com/39537412/67187382-f043f280-f3f6-11e9-827f-5a43115b65fd.png)

من از اخرین آپدیت ویندوز استفاده میکنم:

![image](https://user-images.githubusercontent.com/39537412/67187514-3c8f3280-f3f7-11e9-9a48-54a6b1fa6fb5.png)

**Comment by kokabi1365** [comment]
<div dir="rtl">
آره اینو چند نفر دیگه هم گزارش دادن. احتمال می‌دم به خاطر این باشه که در شروع ویندوز اجرا میشه. یک بار اون گزینه شروع با ویندوز رو از تنظیمات غیرفعال کن، ببین دوباره این اتفاق می‌افته یا نه. برای خود من که از ویندوز 10 بیلد 1903 آخرین آپدیت استفاده می‌کنم این اتفاق نیفتاده. رو سیستم دیگه هم مشکل نداشتم. به هر حال مشکل امنیتی نداره.
</div>
