### ISSUE TITLE
بالانیامدن برنامه

### ISSUE THREAD

**Issue by neesti** [kokabi1365/Vajehdan#17]
<div dir=rtl>
سلام. 
وقتی پنجرهٔ برنامهٔ دیگری (مثلاً گوگل‌کروم) باز باشد، اگر روی آیکون واژه‌دان در سینی سیستم کلیک کنیم، پنجرهٔ واژه‌دان رو نمی‌آید! 

عجیب اینکه این مشکل همیشه وجود ندارد! نمی‌دانم چطور می‌شود که این مشکل رخ می‌دهد. حدس می‌زنم در واقع یک‌جور تأخیر در بالاآمدن برنامه باشد که همیشه هم پیش نمی‌آید.

**Comment by neesti** [comment]
<div dir=rtl>
فکر می‌کنم علت مشکل را پیدا کرده باشم. 
در واقع برنامه بالا می‌آید؛ اما اصطلاحاً On Top نمی‌شود؛ یعنی روی پنجرهٔ بازِ برنامه‌ای که باز است، قرار نمی‌گیرد. 
یعنی چی؟
یعنی اگر مثلاً گوگل‌کروم باز است، اگر روی آیکون واژه‌دان کلیک کنید بالا می‌آید؛ اما پشت پنجرهٔ گوگل‌کروم است و دیده نمی‌شود. کاربر هم فکر می‌کند کلیکش بی‌اثر بوده است و دوباره روی آیکون برنامه کلیک می‌کند؛ در حالی که در همان کلیک اول، پنجرهٔ واژه‌دان بالا آمده بوده.

**Comment by kokabi1365** [comment]
<div dir="rtl">
احتمالاً، تیک نمایش در بالای پنجره را در قسمت تنظیمات نزدید. در نسخۀ بعدی Always On Top رو به صورت اجباری قرار میدم.
</div>
