### ISSUE TITLE
ی و ک فارسی و عربی

### ISSUE THREAD

**Issue by imiimiimi** [kokabi1365/Vajehdan#19]
اگه كلمه‌اي مثل "**براي**" با **ي** عربي تايپ كني چيزي نمياره ولي با **ی** فارسي پيدا ميكنه
پيشنهاد ميشه برنامه تفكيكي بين ي و ك فارسي عربي قائل نشه تا با هر كيبوردي تايپ شد مشكلي پيش نياد
unicode حروف اينان:
**ی = U+06CC**  فارسي
**ي = U+064A**  عربي

**ک = U+06A9**  فارسي
**ك = U+0643**  عربي

**Comment by kokabi1365** [comment]
<div dir="rtl">
این مورد رو برای افزایش سرعت جستجو لحاظ نکردم. سعی می‌کنم در نسخۀ بعدی فکری براش بکنم.
</div>
