### ISSUE TITLE
نادیده نگرفتن کاراکتر فاصله

### ISSUE THREAD

**Issue by Arasteh** [kokabi1365/Vajehdan#20]
وقتی کلمه‌ای در کادر جست‌وجو نوشته می‌شود، اگر **کاراکتر فاصله** ابتدا یا انتهای آن درج شده‌باشد، واژه‌دان نتیجهٔ متفاوتی می‌دهد. پیشنهادم این است که واژه‌دان بعضی از کاراکترها را –از جمله همین **فاصله** و **نیم‌فاصلهٔ** قبل یا بعد از کلمات که معمولاً سهوی هستند– نادیده بگیرد.

**Comment by kokabi1365** [comment]
پیشنهاد خوبی بود. لحاظ می‌کنم.
