### ISSUE TITLE
نسخهٔ لینوکسیِ واژه‌دان

### ISSUE THREAD

**Issue by neesti** [kokabi1365/Vajehdan#21]
<div dir=rtl>
سلام. 
لطفاً نسخهٔ سازگار با لینوکس را نیز منتشر کنید. 
متشکرم.

**Comment by kokabi1365** [comment]
<div dir="rtl">
این کار فعلاً به خاطر یک سری محدودیت‌های فنی و زمانی، در دستور کار نیست. امیدوارم توسعه‌دهندگان دیگری، این پروژه رو برای پلتفرم‌های دیگه توسعه بدن. برنامه‌نویسی چندسکویی کار هزینه‌بری هست و معمولاً برای یک پروژۀ متن‌باز، آن هم به صورت تک نفره امکان‌پذیر نیست.
</div>

**Comment by neesti** [comment]
<div dir=rtl>
سلام. 
این موضوع در انجمن اوبونتو مطرح شده است. 
این‌طور که آقا دانیال گفته‌اند، ظاهراً اگر پایگاهِ دادهٔ این برنامه در فرمت استانداردِ متن‌بازی منتشر بشود، به‌سادگی می‌شود، نسخهٔ لینوکسیِ این برنامه را آماده کرد. 

لینک مبحث در انجمن:
https://forum.ubuntu.ir/index.php?topic=150635.0

**Comment by kokabi1365** [comment]
ممنون از پیگیری شما.
بررسی می‌کنم، اگر امکان تبدیل دیتابیس متنی در زمان معقولی بود، حتماً در اولین فرصت، این کار را می‌کنم.

**Comment by kokabi1365** [comment]
وردنت رو بررسی کردم. تا جایی که متوجه شدم، این پایگاه داده، بیشتر برای یافتن رابطۀ معنایی کلمات و پردازش زبان طبیعی استفاده میشه. از این جهت، امکان تبدیل پایگاۀ داده متنی واژه‌دان به این قالب وجود نداره؛ چون برای این کار لازمه چند صد هزار کلمه در دسته‌بندی مناسب به این پایگاه داده معرفی بشه و اساساً نیازی به این قالب نیست. من نمی‌دونم چرا آقا دانیال، برای ساخت نسخۀ لینوکسی برنامه همچین قالبی رو درخواست کردند! 

با همین فرمت متنی هم می‌توان از دیتابیس برنامه استفاده کرد. نیازی به جداسازی کلمات مترادف و متضاد نیست؛ همه کلمات با یک الگو و حائل مناسب (علامت ،) از یکدیگر جدا شده‌اند. من قبلاً با لینوکس کار کردم، بسیاری از فرهنگ‌ها بر مبنای وردنت نیستند. اساساً مشکل اصلی، پیاده‌سازی برنامه در لینوکس است، باقی کار پارز کردن یک دیتابیس بسیار سادۀ متنی است. دیتابیس، دیتابیس است، متن‌باز و غیرمتن‌باز ندارد. یک نفر آستین بالا بزند، من دیتابیس را به هر فرمتی (Json، SQL, No SQL و ...) تحویل میدهم. مهم الگو داشتن داده‌ها است که دیتابیس متنی واژه‌دان دارد.

**Comment by ravexina** [comment]
> من نمی‌دونم چرا آقا دانیال، برای ساخت نسخۀ لینوکسی برنامه همچین قالبی رو درخواست کردند!

در گنو/لینوکس ابزاری وجود داره به نام
Artha
که کافیه فرمت پایگاه‌داده به شکل استاندارد وردنت بهش تحویل داده بشه و تمام. دیگه نیازی به پیاده سازی نسخه دیگه‌ای وجود نداره. البته این ابزار اشتباه نکنم در سیستم‌عامل‌های دیگه هم قابل استفاده هست

به همین خاطر این موضوع پیشنهاد شد و ربطی به پیاده سازی نسخه گنو/لینوکسی نداشت

**Comment by kokabi1365** [comment]
فرمت استاندارد وردنت نیازمند تفکیک صفات، افعال و اسامی و ... است و متأسفانه چون فرهنگ واژه‌دان به صورت متنی از یک فایل ورد و فاقد چنین تفکیکی استخراج شده، به سختی میشه به فرمت وردنت تبدیل کرد. حتی به نظرم اگه تبدیل هم بشه، تناسبی با ماهیت Artha و نرم‌افزارهای مبتنی بر وردنت نداره. دلیلش اینه که واژه‌دان صرفاً در میان چند هزار سطر جستجو می‌کنه و سطرهایی که شامل کلمه هستند رو نمایش میده. همین الان هم کاربران لینوکس با کپی دیتابیس متنی واژه‌دان به یک فایل متنی در لینوکس و جستجو در اون فایل می‌تونن کار خودشون رو راه بندازن. تنها مشکلش اینه که سهولت و کاربرپسندی یک واسط کاربری رو از دست میدن. ساخت یک واسط کاربری برای جستجو داخل یک فایل متنی، اصلاً کار سختی نیست. کافیه یک توسعه‌دهندۀ لینوکسی یکی دو هفته وقت بزاره.

**Comment by ravexina** [comment]
تقریبا همه این موارد رو که گفتید قبلا تو همون تایپیک گفتگو پیرامون موضوع ایجاد شد مطرح کرده بودم
