### ISSUE TITLE
کرش کردن نسخه 4.1

### ISSUE THREAD

**Issue by imiimiimi** [kokabi1365/Vajehdan#22]
درود،
تو نسخه 4.1 در اکثر مواقع وقتی روی آیکن برنامه راست کلیک میکنم و بین سه منو خروج و راهنما و تنظیمات حرکت میکنم ویندوز برای چند ثانیه هنگ میکنه بعد نرم افزار واجدان ترمینیت میشه و ویندوز ریپورت، این خطا لاگ میکنه:

**Problem Event Name:	APPCRASH
Application Name:	Vajehdan.exe
Application Version:	4.1.0.0
Application Timestamp:	98e27cd6
Fault Module Name:	StackHash_5d8f
Fault Module Version:	0.0.0.0
Fault Module Timestamp:	00000000
Exception Code:	c0000005
Exception Offset:	PCH_ED_FROM_ntdll+0x000723CC
OS Version:	10.0.18363.2.0.0.256.4**

مشکل دیگه اینه وقتی برنامه با با کلید‌های میانبر اجرا میکنم ولی خارج از محدوده کلیک میکنم خارج نمیشه.
اگر هم ممکنه این قابلیت اضافه کنید که با دوبار کلیک روی آیکون نرم افزار اون اجرا بشه.

**Comment by kokabi1365** [comment]
ممنون از شما.
مشکل کلیک خارج از محدوده حل شد. به زودی نسخۀ جدید رو آپلود می‌کنم.
در مورد دوبار کلیک، مرسوم نیست؛ همۀ برنامه‌ها با یکبار کلیک باز میشن از جمله آی دی ام. 
موقع کرش کردن برنامه، یک فایل به نام log.txt در محل اجرای برنامه ساخته میشه. لطفاً اون رو برای من ارسال کنید. این مشکل آیا همیشه به وجود میاد؟ اگر نه چه زمانی؟ متأسفانه لاگ ویندوز اطلاعات زیادی نمیده. برای اینکه بتونم خطا رو برطرف کنم، ابتدا باید برای خودم به وجود بیاد.

**Comment by imiimiimi** [comment]
متاسفانه فایل log.txt ساخته نمیشه ولی میتونم بگم همیشه این اتفاق رخ میده تک و توک شاید پیش نیاد یا اینکه بین منوها حرکت نکنم و مستقیم سراغ یکی از سه منو تا برم و سریع انتخابش کنم

**Comment by kokabi1365** [comment]
وقتی لاگ ساخته نمیشه یعنی یک عامل خارجی برنامه رو می‌بنده. این مشکل 100% به خود سیستم‌عامل و نرم‌افزارهایی مثل آنتی‌ویروس ربط داره. حتی ممکنه برای خودِ [Explorer.exe](https://www.sysnative.com/forums/threads/stackhash-appcrash-issue-windows-7-sp1.18327/) هم پیش بیاد. شما لطف کنید هر آنتی‌ویروس یا برنامه ضد بدافزاری دارید موقتاً غیرفعال کنید. مجددا تست کنید، اگه همچنان مشکل وجود داشت، تمام برنامه‌ها و پراسس‌های مشکوک رو ببندید و دوباره تست کنید. اگه بازم مشکل وجود داشت، در حالت Safe mode تست کنید. تو ویندوز 10 یه قابلیتی هست به اسم Windows Sandbox که باید تو قسمت windows features فعال کنید. برنامه رو بکشید اونجا و تست کنید. یک کار دیگه هم بکنید، از قسمت Advance system settings، تب Advanced و قسمت Performance دکمۀ Settings رو بزنید. از تب Data Execution Preventation گزینۀ اول رو اجرا کنید. اگه گزینۀ اول بود در حالت گزینۀ دوم تست کنید. اگه بتونید تو یک سیستم دیگه هم تست کنید خوب میشه.

**Comment by imiimiimi** [comment]
روی یک سیستم دیگه با همین ویندوز ولی بدون آنتی ویروس چک کردم همین مشکل بود.
توی Sandbox مشکلی نداشت مگر اینکه بلافاصله که برنامه اجرا میشه روش راست کلیک کنی و روی منوها بچرخی.
این مشکل فقط در یک صورت رخ نمیده که بعد از اجرای اولیه برنامه یکبار با دوبار کلیک یا میانبر اجراش بکنم دیگه بعد از اون روی منوها حرکت کنم کرش نمیکنه.

**Data Execution Preventation بی‌تاثیر بود

**Comment by kokabi1365** [comment]
[نسخۀ 4.1.1](https://github.com/kokabi1365/Vajehdan/releases/tag/4.1.1) رو چک کنید. ببینید مشکل حل شده یا نه؟ اگه همچنان مشکل وجود داشت، لطف کنید ابتدا تاریخچۀ تمام لاگ‌های Window Event Viewer رو پاک کنید، خیلی سریع خطا رو دوباره ایجاد کنید و پشت بندش لاگ‌های ایونت ویور رو برام بفرستید. یک کار دیگه هم بکنید، ویندوز و درایورها رو آپدیت کنید و مجددا تست کنید. این مشکل Access Violation هست و به حافظه ربط داره و دلایل مختلفی می‌تونه داشته باشه. هارد شما فضای کافی داره؟ اگه سوزنیه، دفراگش کردید؟ رم شما چند گیگه، مقدار فضای خالی‌اش؟ بعد از اجرای برنامه، مقدار خالی رم چقدر میشه؟

**Comment by kokabi1365** [comment]
یکبار در حالت ادمین برنامه رو چک کنید.

**Comment by kokabi1365** [comment]
اگر براتون مقدور هست، طبق این راهنما، فایل dump رو برام ارسال کنید. اطلاعات بیشتری در اختیارم قرار میده.

**Comment by imiimiimi** [comment]
عالی، تو نسخه 4.1.1 هم مشکل کرش کردن حل شده هم کلیک خارج از محیط و بسته شدن برنامه. خسته نباشید.
