### ISSUE TITLE
جست‌وجوی بعضی کلمات نتیجه ندارد

### ISSUE THREAD

**Issue by Arasteh** [kokabi1365/Vajehdan#23]
در این چند روز به‌صورت رندوم به کلماتی برخورده‌ام که وقتی جست‌وجویشان می‌کنم، نتیجه‌ای نشان داده نمی‌شود. مثلاً «آغاز، آباد، آرام، آسان، …» که به‌نظر می‌رسد براساس یک الگو باشد. اما علاوه‌براین کلمات، جست‌وجوی «کارآزموده، آزمایش، فرایند» هم نتیجه نداشت.

**Comment by kokabi1365** [comment]
بله حق با شماست. در نسخۀ بعدی این مشکل رو حل می‌کنم.
