### ISSUE TITLE
مصوبات فرهنگستان

### ISSUE THREAD

**Issue by neesti** [kokabi1365/Vajehdan#24]
<div dir=rtl>
سلام. 

«واژه‌دان» لغت‌نامه‌ای فارسی به فارسی است. 
به‌نظرتان داخل‌کردنِ اِکسلِ معادل‌های مصوبِ فرهنگستان (دفاتر ۱ تا ۱۲) به این لغت‌نامه، در تضاد با هدفِ این واژه‌نامه است؟

**Comment by kokabi1365** [comment]
سلام.
«واژه‌دان» لغتنامه‌ای برای یافتن کلمات **مترادف و متضاد فارسی** است؛ از همین رو، افزودن لغت‌نامه‌های خوبی مثل معین، دهخدا و ایضاً معادل‌های مصوب فرهنگستان، در تضاد با اهداف این برنامه است.
البته پیشنهاد خوبی بود. ان‌شاءالله در یک برنامۀ دیگر.

**Comment by neesti** [comment]
<div dir=rtl>
البته فرهنگستان، سامانه‌ای برای جست‌وجوی واژه‌های مصوب دارد؛ اما هم همهٔ دفاتر را به آن وارد نکرده‌اند و هم سرعت پاسخ‌گوییِ سرورشان کند است.

**Comment by neesti** [comment]
<div dir=rtl>
ولی خودمانیم، اسم برنامهٔ شما (واژه‌دان) آن‌قدر جامع است که می‌شود هرچیزی را تویِ آن ریخت!

**Comment by kokabi1365** [comment]
<div dir="rtl">
در مورد اسم برنامه حق با شماست. 
راستش اسم برنامه در ابتدا «واژه‌یار» بود و تناسب خوبی هم با هدف برنامه داشت؛ ولی به دلیل مشابهت اسمی برنامه با یک سامانۀ دیگر، تغییر به اسم «واژه‌دان» صورت گرفت تا آن دوستان هم از نگرانی بیرون آیند. البته به قول شما این اسم جدید مضمون جامعی دارد و اینطور می‌نماید که هر واژه‌ای را می‌توان در آن جای داد. متأسفانه دردسرهای ساخت برنامه و رفع اشکالات آن و از همه مهم‌تر مشغله‌های بی‌امان این روزها، مجالی نمی‌دهد تا با یک دل سیر در جزئیات برنامه غرق شوم. 
ممنون از ظریف‌بینی و توجهتان.
</div>

**Comment by kokabi1365** [comment]
> البته فرهنگستان، سامانه‌ای برای جست‌وجوی واژه‌های مصوب دارد؛ اما هم همهٔ دفاتر را به آن وارد نکرده‌اند و هم سرعت پاسخ‌گوییِ سرورشان کند است.
حرفتان کاملاً درست است!
چرا باید یک نهاد فرهنگی اینقدر ضعیف و سنتی عمل کند. این چه سامانۀ جستجویی است که در روز ده بار خطا می‌دهد؛ حداقل سایت را بر روی یک سرور مناسب میزبانی کنید تا اینقدر از دسترس خارج نشود و جستجو در آن کند نباشد. چرا کار را به اهل فن نمی‌دهید که آنطور که شایستۀ مردم است انجام دهند. مگر ساخت یک اپلیکیشن موبایلی یا یک وب‌سایت مدرن چقدر بودجه و زمان می‌خواهد که این همه سالِ مدید، خسته و بی‌رمق حرکت می‌کنید. 
افسوس که در حوزۀ فرهنگ، بیش از آن که کار کنیم، حرف می‌زنیم! امید که روزی چرخ فرهنگ و حمایت از زبان فارسی، به راه افتد؛ البته اگر تا آن روز چیزی از پیکر نحیف زبان فارسی باقی مانده باشد!

**Comment by kokabi1365** [comment]
> سلام.
> «واژه‌دان» لغت‌نامه‌ای فارسی به فارسی است.
> به‌نظرتان داخل‌کردنِ اِکسلِ معادل‌های مصوبِ فرهنگستان (دفاتر ۱ تا ۱۲) به این لغت‌نامه، در تضاد با هدفِ این واژه‌نامه است؟

فایل اکسل معادل‌های مصوب فرهنگستان رو اگه دارید برام بفرستید

**Comment by neesti** [comment]
[واژه‌های مصوب تا دفتر ۱۲.xls.zip](https://github.com/kokabi1365/Vajehdan/files/5652570/xls.zip)

**Comment by kokabi1365** [comment]
<div dir="rtl">خوب مصوبات رو به برنامه اضافه کردم حالا می‌بینم که کتابش به صورت چاپی تحت کپی‌رایت عرضه می‌شه. این فایلی که شما آوردید از کجا آوردید. من که هرچی گشتم نسخهٔ رایگانی حتی PDF از مصوبات پیدا نکردم. فرهنگستان هم چیزی دربارهٔ رایگان بودنش نگفته. لطفاً اگر ارجاعی به این موضوع دارید بدید؛ چون در غیر اینصورت امکانش استفاده ازش نیست و ناچارم از برنامه حذفش کنم.</div>

**Comment by neesti** [comment]
<div dir=rtl>
فایل را چند سال پیش دکتر حمید حسنی، پژوهشگر ارشد گروه واژه‌گزینیِ فرهنگستان، در گروه تلگرامیِ ویراستاران فرستادند. 
از ایشان دربارهٔ مالکیت معنوی این فایل سؤال کردم. هنوز پاسخی نداده‌اند. پاسخ که دادند، عیناً منتقل می‌کنم.

**Comment by kokabi1365** [comment]
<div dir="rtl">
ممنون. منتظر خبرتون هستم.
</div>

**Comment by neesti** [comment]
<div dir=rtl>
شناسهٔ تلگرامشان این است:
@Hamid_Hassani_47
شاید اگر مستقیماً با خودشان تماس بگیرید، زودتر به پاسخ برسید.

**Comment by kokabi1365** [comment]
<div dir="rtl">
کار خوبی کردید.
ممنون.
</div>

**Comment by kokabi1365** [comment]
<div dir="rtl">
این ویژگی به نسخهٔ جدید اضافه شد.
</div>
