### ISSUE TITLE
پرسش از نحوه بیلد پروژه

### ISSUE THREAD

**Issue by alireza-rezaee** [kokabi1365/Vajehdan#27]
<div dir="rtl">
سلام،
<br>
هر بار پس از Build با Error مواجه می شدم تا آنکه این دو خط را از فایل پروژه 
<i>
Vajehdan.csproj
</i>
 حذف کردم. آنگاه درست شد.
</div>
<pre>
&lt;Error Condition="!Exists('..\packages\Xamarin.Forms.3.6.0.344457\build\Xamarin.Forms.props')" Text="$([System.String]::Format('$(ErrorText)', '..\packages\Xamarin.Forms.3.6.0.344457\build\Xamarin.Forms.props'))" /&gt;
&lt;Error Condition="!Exists('..\packages\Xamarin.Forms.3.6.0.344457\build\Xamarin.Forms.targets')" Text="$([System.String]::Format('$(ErrorText)', '..\packages\Xamarin.Forms.3.6.0.344457\build\Xamarin.Forms.targets'))" /&gt;
</pre>
<div dir="rtl">
آیا این مسئله مشکلی در روند اجرای برنامه پیش نمی آورد؟
</div>

**Comment by alireza-rezaee** [comment]
<div dir="rtl">
ممنون، حل شد. الآن دیگه به نظرم نباید مشکلی پیش بیاد.
</div>
see: <a href="https://docs.microsoft.com/en-us/xamarin/cross-platform/troubleshooting/questions/nuget-packages-missing">https://docs.microsoft.com/en-us/xamarin/cross-platform/troubleshooting/questions/nuget-packages-missing</a>

**Comment by kokabi1365** [comment]
<div dir="rtl">راستش من تغییرات #25 رو دیدم و در مورد این دو خطی که حذف کردید هنوز سورس رو بیلد نکردم. به هر حال تغییر بزرگی نیست merge کردم اگه احیاناً بعداً مشکلی بود رول‌بک می‌کنم.<div>
