### ISSUE TITLE
استفاده از HandyControls

### ISSUE THREAD

**Issue by ghost1372** [kokabi1365/Vajehdan#29]
سلام توی توضیحات برنامه دیدم که درخواست هایی برای بهبود رابط کاربری و پیاده سازی تب بصورت بستن و جابجا شدن رو دارید
من پیشنهاد میکنم که از 
[HandyControls](https://github.com/ghost1372/HandyControls)
استفاده کنید
علاوه بر کنترل و استایل ها  شامل کلی اکستنشن متد و هلپر هم هست که کلی از حجم کدنویسی رو کاهش میده

https://hosseini.ninja/handycontrol/extend_controls/tabControl/

![image](https://raw.githubusercontent.com/HandyOrg/HandyOrgResource/master/HandyControl/Resources/TabControl.gif)

**Comment by kokabi1365** [comment]
<div dir="rtl">
اتفاقاً کتابخانهٔ خوبتون رو قبلاً دیدم و خیلی خوشحالم که یک ایرانی سازنده‌ش هست؛ ولی چون به خیلی از کنترل‌هاش نیازی نداشتم مردد بودم استفاده بکنم یا نه. البته هنوز دقیق بررسی‌ش نکردم. باید دقیق‌تر امکاناتش رو بررسی کنم. 

ممنون از پیشنهادتون.
</div>
