### ISSUE TITLE
نسخه وب

### ISSUE THREAD

**Issue by rastikerdar** [kokabi1365/Vajehdan#30]
تشکر می‌کنم برای ایجاد این برنامه و انتشار آزاد آن.
فکر می‌کنم بهتره که از الان به فکر نسخه تحت وب که مثل یک وب‌سایت معمولی در مرورگر اجرا شود (نه الکترون) هم باشید به چند دلیل:

- جامعه میلیونی موبایل و لینوکس و مک از آن محروم نخواهند بود که تعدادشون بیشتر از ویندوزه. من هم به دلیل همین مشکل از این برنامه محرومم
- همه جا در دسترسه. خیلی مواقع پای کامپیوتر نیستیم و یا جایی که هستیم قادر به نصبش نیستیم
- دنیا به سمت وب سرویس رفته مگر اینکه واقعا چاره‌ای نباشه
- برای آپدیت‌ها نیازی نیست برنامه آپدیت بشه و به‌روزرسانی وبسایت یعنی به‌روزرسانی برای همه. سریع تر می‌تونید تغییر بدهید یا امکانات جدید اضافه کنید و ...
- خیلی بیشتر و بهتر می‌تونید جامعه کاربری و نحوه تعامل و درخواست‌هایش رو بشناسید و پیاده کنید
- میتونید ‌‌ای‌پی‌آی بدید تا بشه کلاینت‌های دیگر برایش نوشت. از اپ موبایل گرفته تا استفاده در دیگر برنامه‌ها
- امکانات ویژه و یا حتی پولی بدهید چه برای توسعه‌دهنده‌ها و چه کاربران
- و دلایل دیگر که دیگر دست من خسته شد :)

راستش من اولین بار که دیدم پیش خودم گفتم چرا برنامه به این خوبی تحت وب نیست!

**Comment by rastikerdar** [comment]
البته من الان یادم اومد که یه وبسایت معروف در همین زمینه خیلی وقته فعال و در حال سرویس‌دهی است و اینکه شاید اصلا هدف این برنامه شما اتفاقا کارکرد آفلاین و سریعش بوده. با عرض پوزش اگر وقتتون رو گرفتم.

**Comment by kokabi1365** [comment]
<div dir="rtl">
ممنونم.
نه خواهش می‌کنم. اتفاقاً خیلی خوبه اینطور تفصیلی مزایایِ وب رو نوشتید. بعضی‌هاش تا الان به ذهنم نرسیده بود.
اول اینو بگم که فکر نمی‌کنم مجموعِ تعدادِ کاربران بقیهٔ پلتفرم‌ها روی هم بیشتر از ویندوز باشه!
<br/><br/>
سرویسِ واژه‌یاب خیلی وقته در بسترِ وب در دسترسه؛ ولی هیچ‌وقت نتونستم به صورتِ فعال ازش استفاده کنم. همون یه‌ذره تأخیر در نمایشِ نتایج (به خاطرِ ماهیتِ وب) باعث می‌شه نتونید به صورتِ فعال ازش استفاده کنید. یکی از دلایلی که باعث شد واژه‌دان رو بسازم آفلاین بودن و سرعتِ دسترسی بالاست. درسته که خیلی از کاربرانِ غیرویندوزی از این برنامه بی‌بهره‌ن؛ ولی به دلایلی که عرض کردم فکر نمی‌کنم نسخهٔ وب کارآمدی لازم رو داشته باشه. 
<br/><br/>
به همین خاطر بیشتر دنبالِ راهکاری برای کراس‌پلتفرم‌کردنِ برنامه از طرقی غیر از وب و الکترون هستم؛ مثلاً با پلتفرم‌ِ QT؛ ولی متأسفانه تخصصی در QT ندارم و انجامِ این کارها مستلزمِ همکاریِ بقیهٔ توسعه‌دهندگان است. با این حال نمی‌شه به این امید نشست. نسخهٔ وب باوجودِ ناکارآمدی لااقل می‌تونه برایِ کاربرانِ بقیهٔ پلتفرم‌ها کارراه‌انداز باشه. ایدهٔ API هم جالب بود. شاید باید در دیدگاهم تجدید نظر کنم.
<br/><br/>
ممنون از وقتی که گذاشتید.
</div>

**Comment by mimsadAlef** [comment]
اگه نظر من به عنوان یه نوجوون رو حساب می کنید
اگه با html و css و js نوشته بشه می تونید با الکترون برای دسکتاپ و با ری اکت نیتیو برای اندروید و آی او اس بنویسید و حتی نسخه آنلاین هم داشته باشید

**Comment by kokabi1365** [comment]
<div dir="rtl">
ممنون از پیشنهادتون.
همینکه به عنوانِ یک نوجوون در گیتهاب حضور دارید یعنی از خیلی‌ها جلوتر هستید.
من به دلایلی که به بخشی از اون‌ها بالاتر اشاره کردم نسخهٔ وب و راهکارهایِ کراس‌پلتفرمی مثل الکترون و React Native رو نمی‌پسندم. برایِ راهکارهایِ الکترون و ری‌اکت‌نیتیو دلایلِ فنی هم دارم که اینجا نمی‌خوام بهش بپردازم. حتی اگر بحثِ تخصص رو کنار بذاریم فرصتِ کافی برای کارکردنِ تمام‌وقت رویِ این پروژه ندارم. در هر حال پروژه متن بازه و هرکسی می‌تونه پا پیش بگذاره؛ مخصوصاً شما جووون‌ترهایِ سرشار از انرژی... 🙂
</div>

**Comment by ohmydevops** [comment]
سلام جناب کوکبی عزیز، برای نسخه لینوکس شما برنامه‌ریزی خاصی کردین؟ یا فردی برای پیاده‌سازیش اقدام کرده؟ من نگاه کردم سایت رو متوجه نشدم برای این موضوع فعالیت خاصی صورت گرفته یا نه ولی اگر کاری انجام نشده من چند وقت دیگه بعد از امتحاناتم تمایل دارم برای نسخه لینوکس کمک کنم.

**Comment by kokabi1365** [comment]
<div dir="rtl">
سلام آقای بقایی.

نه تا الان کسی اقدامی نکرده. 

تنها گزینه‌ای که بدون تغییراتِ زیاد در کدبیس و با دانشِ فعلی می‌تونستم برنامه رو کراس‌پلتفرم کنم Avalonia بود که اونم متأسفانه از زبانِ فارسی پشتیبانی نمی‌کنه. در حالِ حاضر تنها روزنهٔ امید  NET MAUI. هست که هنوز نسخهٔ رسمی بیرون نداده. 

به نظرم چون نسخهٔ جدید تازه منتشر شده، یه پنج شش ماهی صبر کنیم ببینیم استقبال چطوره؛ چون بالاخره بخشِ زیادی از کاربران، ویندوزی هستن و این می‌تونه نمونهٔ آماری خوبی باشه. اگه تعدادِ کاربران کم باشه دلیلی نداره کلی وقت بذارید و برای یک پلتفرم دیگه از صفر کدنویسی کنید (چون می‌دونم زحمتِ و وقتِ‌ زیادی می‌طلبه.) مگه اینکه اولویتِ خاصی نداشته باشید و بخواهید حتی برای اقلیتی از کاربران، خلقِ ارزش کنید. 

اشتباهٔ من این بود که یه راهی برای سنجشِ تعدادِ کاربرانِ فعال برنامه پیش‌بینی نکردم. الان تو گیتهاب ۲۵۰۰ نفر برنامه رو دانلود کردن ولی نمی‌دونم چند درصدشون کاربرِ فعال هستن. در حالِ حاضر دنبالِ راهی هستم که تعدادِ کاربرانِ فعالِ برنامه رو به دست بیارم. اگه بشه همچین برآوردی داشت بهتر می‌شه برایِ آینده برنامه‌ریزی کرد.

بهترین روشی که به ذهنم رسیده اینه که در آپدیتِ بعدی کدی به برنامه اضافه کنم که میزانِ استفاده از برنامه رو محاسبه کنه و ارسال کنه. اینطوری خیلی راحت می‌شه فهمید چندنفر از کاربران واقعاً از برنامه استفاده می‌کنن.

</div>

**Comment by ohmydevops** [comment]
<div dir='rtl'>

مادر من یکی از کابران فعال این برنامه هستش و هر روز توی کارای ویرایشی استفاده میکنه و خیلی هم سازنده‌شو دعا میکنه :)

برای بحث پشتیبانی در پلتفرم‌های دیگه همونطور که خودتون گفتین، بهترین کار، کراس‌پلتفرم کردن هستش که من تخصصی در این زمینه در حوزه دات‌نت ندارم. البته مدتیه به خاطر پروژه‌ای درگیر چارچوب الکترون‌جی‌اس شدم و به نظر عملکرد خوبی داره و متوجه شدم شما به دلایلی تمایلی به استفاده از این چارچوب ندارید. البته قطعا برنامه Native چیز دیگریست و تجربه بهتری برای مخاطبان داره.

به‌هرحال، بودن این نرم‌افزار در محیط‌های لینوکسی، به نظرم ارزش خوبی برای مخاطبان محدود این پلتفرم داره که شاید برای شروع بشود فقط امکانات خیلی پایه‌ای رو توی نسخه مخصوص پلتفرم لینوکس آورد و به مرور تکمیلش کرد.

اگر به نظر شما، زمانی نیاز بود نسخه لینوکسی این برنامه ارزشمند ساخته بشه، من میتونم وقتی رو بهش اختصاص بدم و میتونید روی من حساب کنید.

</div>

**Comment by kokabi1365** [comment]
<div dir="rtl">
خوشحالم که فعالانه استفاده می‌کنن. خدانگهدارشون باشه.

قطعاً اگر لازم شد برای نسخهٔ لینوکسی از شما کمک می‌گیرم. البته پروژه متن‌بازه و اجازه‌ش دستِ من نیست. می‌تونید Fork بگیرید و به صلاحدیدِ خودتون برای هر پلتفرمی و با هر روشی توسعه بدید. مطالبی که گفتم صرفاً بیانِ نظراتِ شخصی است و برای این هست که احیاناً وقتِ کسی الکی تلف نشه. مثلاً یکی ممکنه بیاد چند ماه وقت بذاره و برنامه رو برایِ پلتفرمِ موبایل توسعه بده. کارِِ خوبیه ولی با شناختی که از پلتفرمِ موبایل و کاربردِ خاصِ این برنامه دارم بعید می‌دونم کسی بتونه تو موبایل خیلی ازش استفاده کنه.
</div>

**Comment by ohmydevops** [comment]
<div dir='rtl'>

من هم موافقم که عملا مخاطب اصلی شما در ویندوز وجود داره. البته اگر همچین نرم‌افزار خوبی در محیط لینوکس هم قابل استفاده میبود، حتما کم کم مخاطبان خودش رو پیدا میکرد. من سعی میکنم در تایم‌های آزاد روی نسخه لینوکسی خیلی سبک با حفظ ظاهر ویندوزی کار کنم حداقل اینطوری خودم میتونم در محیط دسکتاپی سیستم‌عامل شخصی خودم، به صورت آفلاین استفاده کنم.

</div>

**Comment by kokabi1365** [comment]
<div dir="rtl">
چرا که نه.
خیلی هم عالی.
</div>

**Comment by ohmydevops** [comment]
این ایشو باید باز بمونه؟

**Comment by kokabi1365** [comment]
<div dir="rtl">
خودمم نمی‌دونم. شاید دوستانِ دیگه‌ای هم بخوان نظراتشون رو بگن.
نظرِ شما چیه؟
</div>
