### ISSUE TITLE
نسخه 32 بیتی

### ISSUE THREAD

**Issue by runo280** [kokabi1365/Vajehdan#38]
لطفا نسخه 32 بیتی رو هم ارائه بدین
توی ادارات برنامتون به کار میاد ولی معمولا سیستم ها ضعیف و قدیمی هستن و سیستم عامل 64 بیتی نیست

**Comment by runo280** [comment]
اصلا برنامه روی ویندوز هفت کار نمیکنه، اشتباه از من بود

**Comment by kokabi1365** [comment]
نسخه‌های جدید روی Windows 7 SP 1 قابل اجراست؛ به شرطی که آخرین آپدیت‌های ویندوز رو نصب کنید. البته من دسترسی به ویندوز ۷ ندارم و تست نکردم.

**Comment by kokabi1365** [comment]
Duplicate of #44
