### ISSUE TITLE
Linux support :)

### ISSUE THREAD

**Issue by Revisto** [kokabi1365/Vajehdan#39]

**Comment by GihanSoft** [comment]
This is written in WPF. so... impossible for now. maybe after MAUI release...
I'm not part of this App's dev team.

**Comment by kokabi1365** [comment]
<div dir="rtl">
سلام.
در رابطه با [نسخهٔ لینوکسیِ واژه‌دان](https://github.com/kokabi1365/Vajehdan/discussions/32) قبلاً هم دوستانی پیشنهاد دادند و بحث‌هایی انجام شده؛ ولی چون این کار نیازمند تغییر کاملِ کدبیس در پلتفرم‌های مختلفه فعلاً مقدور نیست. به قول دوستمون باید منتظرِ فریم‌ورک کراس‌پلفترم MAUI بمونیم. البته به خاطرِ زیادشدنِ درخواست‌ها از کاربرانِ سایرِ پلتفرم‌ها احتمالاً تا اون زمان [نسخهٔ وب](https://github.com/kokabi1365/Vajehdan/discussions/31) رو بسازم.
با اجازه‌تون من این Issue رو می‌بندم. اگر صحبتی باقی مونده در قسمتِ [Discussions ](https://github.com/kokabi1365/Vajehdan/discussions)ادامه بدید.
سپاسگزارم.
</div>
