### ISSUE TITLE
Error in opening

### ISSUE THREAD

**Issue by amirasaadi** [kokabi1365/Vajehdan#40]
I get this error after first install when I open the program.

Can't register the hot key.
Saved in the log file

**Comment by zanasaed** [comment]
me too.

**Comment by kokabi1365** [comment]
<div dir="rtl">
سلام.
عذر می‌خوام دیر جواب می‌دم.
به احتمال زیاد یک برنامهٔ دیگه در سیستم قبل از واژه‌دان اجرا می‌شه و دقیقاً همین کلید ترکیبی (دوبار ALT) رو برای خودش استفاده می‌کنه. در این حالت واژه‌دان که بعد از اون برنامه اجرا می‌شه نمی‌تونه اون کلید ترکیبی رو تخصیص بده. برای حل مشکل باید اون برنامه رو پیدا کنید و کلید ترکیبی رو به چیز دیگه‌ای تغییر دهید. لطفاً خبرش رو بهم بدید.
</div>

**Comment by amirasaadi** [comment]
سلام
من تو این دو روز هر بار که نرم‌افزار رو اجرا کردم. دیگه این خطا رو نگرفتم. پس بنظر تنها در اولین اجرای پس از نصب دیده میشه روی سیستم من.

**Comment by kokabi1365** [comment]
<div dir="rtl">
خب الحمدلله مشکل جدی نبود.
</div>
