### ISSUE TITLE
.Net 5.0 End Of Life

### ISSUE THREAD

**Issue by alireza-rezaee** [kokabi1365/Vajehdan#43]
<div dir='rtl'>
با سلام و احترام، وقت شما بخیر.

در مورد SDK پروژه، [دات‌نت 5.0](https://dotnet.microsoft.com/en-us/download/dotnet/5.0)، به نظر می‌رسد که از میانه اردیبهشت‌ماه از [چرخه حیات توسعه](https://dotnet.microsoft.com/en-us/platform/support/policy/dotnet-core#lifecycle) خارج شده است.

</div>

https://github.com/kokabi1365/Vajehdan/blob/9972c26b92040d153bb6946b507bcb70fbc6ba42/src/Vajehdan/Vajehdan.csproj#L3-L12

**Comment by kokabi1365** [comment]
<div dir="rtl">
ممنون که اطلاع دادید. 
در اولین بروزرسانی کد به دات‌نت ۶ انتقال می‌دم.
</div>

**Comment by kokabi1365** [comment]
<div dir="rtl">
[نسخهٔ ۵.۲.۲](https://github.com/kokabi1365/Vajehdan/releases/tag/v5.2.2) به دات‌نت ۶ بروزرسانی شد. ممنون از شما.
</div>
