### ISSUE TITLE
نسخه پورتابل در Release

### ISSUE THREAD

**Issue by GihanSoft** [kokabi1365/Vajehdan#45]
سلام. در صورت امکان نسخه پورتابل هم قرار بدید برای دانلود.

**Comment by kokabi1365** [comment]
<div dir="rtl">
به روی چشم.
</div>

**Comment by GihanSoft** [comment]
ممنون

**Comment by kokabi1365** [comment]
<div dir="rtl">
نسخهٔ پرتابل اضافه شد.

https://github.com/kokabi1365/Vajehdan/releases/tag/5.2.4

</div>
