### ISSUE TITLE
اضافه کردن نسخهٔ کم‌حجم برای به‌روزرسانی سریع

### ISSUE THREAD

**Issue by Arasteh** [kokabi1365/Vajehdan#48]
سلام
ممنون بابت به‌روزرسانی‌های اخیر که عملکرد برنامه را خیلی بهتر کرده‌اند.
به‌نظرم رسید بهتر است در کنار فایل‌های کامل و پرتابل، یک نسخهٔ کم‌حجم هم عرضه شود که فقط شامل فایل‌های اصلی برنامه منهای پیش‌نیازهای نرم‌افزاری باشد. این مدل عرضه برای کسانی که برنامه و همهٔ پیش‌نیازهایش را از قبل دارند مناسب‌تر است.

**Comment by kokabi1365** [comment]
<div dir="rtl">
سلام.

ممنون از پیشنهاد شما. 
از نسخهٔ بعدی حتماً نسخهٔ نصبیِ بدون پیش‌نیاز رو قرار می‌دم.
</div>

**Comment by Arasteh** [comment]
سلام.
ممنون از توجهتان.
هنوز برای قضاوت زود است؛ اما چون الآن به‌روزرسانی را در واژه‌دان دیدم که به همان فایل کامل لینک شده بود، خواستم بگویم اگر لینک به‌روزرسانی، به فایل کم‌حجم ارجاع داده شود حتماً بهتر است.
اگر هم از قبل به فکرش بوده‌اید و انجام شده: دست مریزاد، این پیام را نادیده بگیرید :)

**Comment by kokabi1365** [comment]
<div dir="rtl">
منطق حکم می‌کنه که بی‌دردسرترین نسخه رو برای دانلودِ پیش‌فرض بگذاریم. البته ایراد شما کاملاً وارده و من راه‌حل بهتری ( #57) برای اون در نظر گرفتم که ان‌شاءالله در نسخه‌های بعدی سراغش می‌رم.

</div>
