### ISSUE TITLE
پیدانشدن کلمات همزه‌دار

### ISSUE THREAD

**Issue by kokabi1365** [kokabi1365/Vajehdan#55]
<div dir="rtl">
کلمات همزه‌دار مثل «زنجیرهٔ جانبی» به هیچ شکلی در نتایج جستجو ظاهر نمی‌شود.
</div>

**Comment by alireza-rezaee** [comment]
نتیجۀ جست‌وجوی عبارت «بندهٔ تو» و «پاشنهٔ»:

تعداد واقعی «بندهٔ تو»:
- گنجور: ۷۴ بار

![image](https://user-images.githubusercontent.com/55509086/187651463-9622f965-2e4a-4dce-a582-a86def74d7a4.png)

تعداد واقعی «پاشنهٔ»:
- فرهنگستان: ۲۸ بار
- گنجور: ۱ بار
- طیفی: ۱ بار

![image](https://user-images.githubusercontent.com/55509086/187654523-60a23f63-f1c7-4d6c-b761-9420b8603aa3.png)
