### ISSUE TITLE
Search issue for words within the Farhangestan dictionary

### ISSUE THREAD

**Issue by alireza-rezaee** [kokabi1365/Vajehdan#56]
جست‌وجوی واژگانی مانند «**add-in**» یا «**take-off**» (و محتویات این واژگان – مانند «**درافزا**» برای «add-in» یا «**برخاست نافرجام**» برای «take-off») که دارای الگوی زیر هستند بی‌نتیجه می‌ماند:

Regex: `[a-zA-Z]+-[a-zA-Z]+`

همۀ واژگان یافت‌شده از این الگو از [«واژه‌های مصوب فرهنگستان زبان و ادب فارسی»](https://github.com/alireza-rezaee/Vajehdan/blob/1d45c1af8ff1633120cccb302c95a8efbba01759/src/Vajehdan/Resources/Dicts/Farhangestan.dic) هستند.

ظاهراً عبارت «زنجیرهٔ جانبی» که در #55 و #51 مطرح شده است طبق همین قاعده از نمایش در نتایج بازمی‌ماند. در واقع این واژه پیرو واژۀ «side-chain» آورده‌شده‌است.

**Comment by alireza-rezaee** [comment]
با کنار هم قراردادن [این مورد](https://github.com/kokabi1365/Vajehdan/issues/55#issuecomment-1232740913)، به نظر می‌رسد مسئلۀ یافت‌نشدن این واژه‌ها (#55 و #56) ارتباطی به این الگوی خاص نداشته باشد. شاید مشکل از سوی نحوۀ جست‌وجو در این فرهنگ‌نامۀ خاص باشد.

**Comment by kokabi1365** [comment]
<div dir="rtl">
باگ بسیار بزرگیه.
باید در اولین فرصت بررسی بشه.
</div>
