### ISSUE TITLE
ری‌ست شدن تنظیمات برنامه بعد از به‌روزرسانی

### ISSUE THREAD

**Issue by Arasteh** [kokabi1365/Vajehdan#65]
این‌طور که متوجه شدم، با هربار به‌روزرسانی واژه‌دان، تیک «شروع برنامه با ویندوز» دوباره فعال می‌شود.
تنظیمات دیگر را بررسی نکرده‌ام؛ اما احتمال دارد همه‌شان همین‌طور باشند.

**Comment by kokabi1365** [comment]
<div dir="rtl">
ممنونم. بررسی می‌کنم.
</div>

**Comment by kokabi1365** [comment]
<div dir="rtl">
من بررسی و تست کردم مشکلی نبود.
آیا منظور شما رو درست متوجه شدم؟
</div>

https://user-images.githubusercontent.com/44271870/190843982-1eb17556-1934-46da-90f8-d8f3d15f6506.mp4

**Comment by Arasteh** [comment]
عجیب است الآن که دوباره امتحان کردم مشکلی پیش نیامد. شاید کم‌دقتی از سمت من بوده باشد.
